### ISSUE TITLE
Please bundle libmvec.so.1 in the AppImage

### ISSUE THREAD

**Issue by probonopd** [blupi-games/planetblupi-dev#6]
Please bundle `libmvec.so.1` in the AppImage. Currently it fails with

```
error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/357#issuecomment-364584377

**Comment by Skywalker13** [comment]
Arf, thanks... It's strange that this lib is now a dep :-( It was not the case with my previous version and I'm using debian stretch for creating the AppImage...

**Comment by probonopd** [comment]
Are you using `linuxdeployqt` to let it determine the dependencies?

**Comment by Skywalker13** [comment]
Not, yet...

**Comment by probonopd** [comment]
It would do this kind of stuff automatically and might be less error prone.

**Comment by Skywalker13** [comment]
It should be integrated to your tool; no?

**Comment by probonopd** [comment]
What do you mean by "your tool"? `linuxdeployqt` _should_ do this automatically.

**Comment by Skywalker13** [comment]
This tool "appimagetool-x86_64.AppImage" after creating the AppImage

**Comment by probonopd** [comment]
`appimagetool` just converts the AppDir into an AppImage. It does not change the contents of the AppDir. For this type of functionality you need to use `linuxdeployqt`.

**Comment by Skywalker13** [comment]
I was thinking to something more like a linter (for example lintian for the Debian packages). I don't want a tool that changes my AppDir but just a linter instead.

**Comment by probonopd** [comment]
We have this as an online tool running on Travis CI at https://github.com/AppImage/appimage.github.io/blob/master/code/worker.sh

**Comment by Skywalker13** [comment]
Fixed by using an older version of the glib
