### ISSUE TITLE
Mission 3 Complete Itself

### ISSUE THREAD

**Issue by mrRosset** [blupi-games/planetblupi-dev#7]
When starting Mission 3 (Building a wall to prevent the fire) the mission automatically finish with a win ~5s after the start of the mission. Without any input from the player.

It doesn't matter if the mission is in easy or hard mode.

Tested On:
Windows 10 x64 build 1709.
PlanetBlupi v1.12.3 x64 in French

**Comment by Skywalker13** [comment]
Oh, good catch.. it works when using the `--restore-bugs` command line argument. I've added a regression by fixing a bug.

**Comment by Skywalker13** [comment]
Fixed by https://github.com/blupi-games/planetblupi/commit/c08b750804b21a802626e7822e1ee682dda1c5c9

I will release v1.12.4 asap
Thanks
