### ISSUE TITLE
"MSYS Makefiles" generator is not permitted by FFmpeg

### ISSUE THREAD

**Issue by jummy0** [blupi-games/planetblupi-dev#9]
Readme.md recommends using the Cmake command-line argument `-G"MSYS Makefiles"` on Windows. FFmpeg disallows this and throws an error during Make configuration:
`Native MSYS builds are discouraged, please use the MINGW environment.`

**Comment by Skywalker13** [comment]
I'm using MINGW provided by MSYS2, not MSYS which is a very old project. FFmpeg assumes that's the old MSYS stuff and it's not the case here.

**Comment by jummy0** [comment]
Ah, understood.  I am now using MSYS2 MinGW 64-bit and running Cmake with `-G"MSYS Makefiles"` is working fine.  Thank you.
